### PR TITLE
Yy feature fixsettingspage

### PR DESCRIPTION
**Pull request by yenyin262**
-wrapped touchable opacity around text 
-update styling for settings

### CODE REVIEW

**Review by piahmed — CHANGES_REQUESTED** [review]
@yenyin262 Again, there are changes from another branch here. Please clean up. Thanks!

**Review by iyuvraajsingh — APPROVED** [review]

**Review by iyuvraajsingh — CHANGES_REQUESTED** [review]
Please resolve merge conflicts.
Thanks

**Review by iyuvraajsingh — DISMISSED** [review]

**Review by iyuvraajsingh — APPROVED** [review]

**Review by piahmed — APPROVED** [review]
Approving this since merging is blocked for some reason.

**Review by iyuvraajsingh — CHANGES_REQUESTED** [review]
Please fix the merge conflicts.

Thanks

**Review by iyuvraajsingh — APPROVED** [review]

**Pull request merged**
